// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package object

import "strconv"

const (
	_ObjectType_name_0 = "TypeErrorTypeNumber"
	_ObjectType_name_1 = "TypeBool"
	_ObjectType_name_2 = "TypeString"
	_ObjectType_name_3 = "TypeArray"
	_ObjectType_name_4 = "TypeHash"
	_ObjectType_name_5 = "TypeNull"
	_ObjectType_name_6 = "TypeReturn"
	_ObjectType_name_7 = "TypeFn"
	_ObjectType_name_8 = "TypeBuiltin"
)

var (
	_ObjectType_index_0 = [...]uint8{0, 9, 19}
)

func (i ObjectType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ObjectType_name_0[_ObjectType_index_0[i]:_ObjectType_index_0[i+1]]
	case i == 4:
		return _ObjectType_name_1
	case i == 8:
		return _ObjectType_name_2
	case i == 16:
		return _ObjectType_name_3
	case i == 32:
		return _ObjectType_name_4
	case i == 64:
		return _ObjectType_name_5
	case i == 128:
		return _ObjectType_name_6
	case i == 256:
		return _ObjectType_name_7
	case i == 512:
		return _ObjectType_name_8
	default:
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
