// Code generated by "stringer -type=ObjectType"; DO NOT EDIT

package object

import "fmt"

const (
	_ObjectType_name_0 = "TypeErrorTypeNumber"
	_ObjectType_name_1 = "TypeBool"
	_ObjectType_name_2 = "TypeString"
	_ObjectType_name_3 = "TypeArray"
	_ObjectType_name_4 = "TypeHash"
	_ObjectType_name_5 = "TypeNull"
	_ObjectType_name_6 = "TypeReturn"
	_ObjectType_name_7 = "TypeFn"
	_ObjectType_name_8 = "TypeBuiltin"
)

var (
	_ObjectType_index_0 = [...]uint8{0, 9, 19}
	_ObjectType_index_1 = [...]uint8{0, 8}
	_ObjectType_index_2 = [...]uint8{0, 10}
	_ObjectType_index_3 = [...]uint8{0, 9}
	_ObjectType_index_4 = [...]uint8{0, 8}
	_ObjectType_index_5 = [...]uint8{0, 8}
	_ObjectType_index_6 = [...]uint8{0, 10}
	_ObjectType_index_7 = [...]uint8{0, 6}
	_ObjectType_index_8 = [...]uint8{0, 11}
)

func (i ObjectType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ObjectType_name_0[_ObjectType_index_0[i]:_ObjectType_index_0[i+1]]
	case i == 4:
		return _ObjectType_name_1
	case i == 8:
		return _ObjectType_name_2
	case i == 16:
		return _ObjectType_name_3
	case i == 32:
		return _ObjectType_name_4
	case i == 64:
		return _ObjectType_name_5
	case i == 128:
		return _ObjectType_name_6
	case i == 256:
		return _ObjectType_name_7
	case i == 512:
		return _ObjectType_name_8
	default:
		return fmt.Sprintf("ObjectType(%d)", i)
	}
}
